name: flutter_group_chat_app_with_firebase
description: A Flutter Group Chat App with Firebase

publish_to: 'none'
version: 1.0.0+1
environment:
  sdk: '>=3.0.5 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  msh_checkbox: ^2.0.1
  cupertino_icons: ^1.0.6
  intl: ^0.18.1
  dartz: ^0.10.1
  get_it: ^7.6.4
  firebase_core: ^2.16.0
  cloud_firestore: ^4.9.2
  firebase_auth: ^4.10.0
  collection: ^1.17.2
  cloud_functions: ^4.4.2
  synchronized: ^3.1.0
  firebase_messaging: ^14.7.3
  stream_d: ^0.3.0
  agora_rtc_engine: ^6.2.4
  agora_uikit: ^1.3.7
  sliding_up_panel: ^2.0.0+1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.3
  flutter_launcher_icons: "^0.13.1"

flutter:
  uses-material-design: true

  assets:
    - assets/
    - assets/fonts/RedHatDisplay/

  fonts:
    - family: RedHatDisplay
      fonts:
        - asset: assets/fonts/RedHatDisplay/RedHatDisplay-Light.ttf
          weight: 100
          style: normal
        - asset: assets/fonts/RedHatDisplay/RedHatDisplay-LightItalic.ttf
          weight: 100
          style: italic
        - asset: assets/fonts/RedHatDisplay/RedHatDisplay-Light.ttf
          weight: 200
          style: normal
        - asset: assets/fonts/RedHatDisplay/RedHatDisplay-LightItalic.ttf
          weight: 200
          style: italic
        - asset: assets/fonts/RedHatDisplay/RedHatDisplay-Regular.ttf
          weight: 300
          style: normal
        - asset: assets/fonts/RedHatDisplay/RedHatDisplay-Italic.ttf
          weight: 300
          style: normal
        - asset: assets/fonts/RedHatDisplay/RedHatDisplay-Medium.ttf
          weight: 400
          style: normal
        - asset: assets/fonts/RedHatDisplay/RedHatDisplay-MediumItalic.ttf
          weight: 400
          style: italic
        - asset: assets/fonts/RedHatDisplay/RedHatDisplay-SemiBold.ttf
          weight: 500
          style: normal
        - asset: assets/fonts/RedHatDisplay/RedHatDisplay-SemiBoldItalic.ttf
          weight: 500
          style: italic
        - asset: assets/fonts/RedHatDisplay/RedHatDisplay-Bold.ttf
          weight: 600
          style: normal
        - asset: assets/fonts/RedHatDisplay/RedHatDisplay-BoldItalic.ttf
          weight: 600
          style: italic
        - asset: assets/fonts/RedHatDisplay/RedHatDisplay-ExtraBold.ttf
          weight: 700
          style: normal
        - asset: assets/fonts/RedHatDisplay/RedHatDisplay-ExtraBoldItalic.ttf
          weight: 700
          style: italic
        - asset: assets/fonts/RedHatDisplay/RedHatDisplay-BlackItalic.ttf
          weight: 800
          style: italic
        - asset: assets/fonts/RedHatDisplay/RedHatDisplay-BlackItalic.ttf
          weight: 800
          style: italic
