// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAKNXcJNWYSKUWbQWHqwsViijI8ZUL1isE',
    appId: '1:368246340671:web:d7e7372e3d67c873c5cc8a',
    messagingSenderId: '368246340671',
    projectId: 'flutter-group-chat-9db9c',
    authDomain: 'flutter-group-chat-9db9c.firebaseapp.com',
    storageBucket: 'flutter-group-chat-9db9c.appspot.com',
    measurementId: 'G-QBGB1DW9C4',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCvyoHT83cKH3MMTCNCvD9cSWtrE3GGlQ4',
    appId: '1:368246340671:android:7ae94e73983a9cbac5cc8a',
    messagingSenderId: '368246340671',
    projectId: 'flutter-group-chat-9db9c',
    storageBucket: 'flutter-group-chat-9db9c.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD1h3u4FRuJct6EYjaYjOH4XhhInXAskok',
    appId: '1:368246340671:ios:d6ee087be546bcbcc5cc8a',
    messagingSenderId: '368246340671',
    projectId: 'flutter-group-chat-9db9c',
    storageBucket: 'flutter-group-chat-9db9c.appspot.com',
    iosBundleId: 'com.example.fluttergroupchatappwithfirebase',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD1h3u4FRuJct6EYjaYjOH4XhhInXAskok',
    appId: '1:368246340671:ios:d6ee087be546bcbcc5cc8a',
    messagingSenderId: '368246340671',
    projectId: 'flutter-group-chat-9db9c',
    storageBucket: 'flutter-group-chat-9db9c.appspot.com',
    iosBundleId: 'com.example.fluttergroupchatappwithfirebase',
  );
}
